server:
  port: 8050

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: "Order"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8090/"

cloudinary:
  cloud-name: dl7atizzb
  api-key: 145491984531442
  api-secret: 1iZYfLLIkyl9QGDTreYx3r-5Mcc
  avatar-upload-folder: XianweiECommerce/UserAvatar
  category-upload-folder: XianweiECommerce/Category
  item-upload-folder: XianweiECommerce/Item

payment:
  service:
    url: http://localhost:8060/api/payment

itemservice:
  url: http://localhost:8040/api/item

userservice:
  url: http://localhost:8070/api/user

cardservice:
  url: http://localhost:8070/api/cards

orderservice:
  url: http://localhost:8050/api/orders

cartservice:
  url: http://localhost:8070/api/cart

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}