server:
  port: 8050

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8075/eureka/

spring:
  application:
    name: "Order"

  datasource:
    url: jdbc:mysql://localhost:3306/orderservice
    username: root
    password: wxwwxw123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

keycloak:
  auth-server-url: http://localhost:7080
  realm: XianweiECommerce
  client-id: xianwei-ecommerce-monolith-client
  client-secret: 4M8WYjvd1HV1WLvMGxZUhV60IKADbIxH
  master-id: xianwei-ecommerce-monolith-client
  master-secret: kHn11XuL8pytqXTW2eQiK6l6VlT8DYlc
  admin-username: admin
  admin-password: admin

cloudinary:
  cloud-name: dl7atizzb
  api-key: 145491984531442
  api-secret: 1iZYfLLIkyl9QGDTreYx3r-5Mcc
  avatar-upload-folder: XianweiECommerce/UserAvatar
  category-upload-folder: XianweiECommerce/Category
  item-upload-folder: XianweiECommerce/Item

payment:
  service:
    url:
      http://localhost:8060/api/payment

itemservice:
  url: http://localhost:8040/api/item

userservice:
  url: http://localhost:8070/api/user

cardservice:
  url: http://localhost:8070/api/cards

orderservice:
  url: http://localhost:8050/api/orders