CREATE TABLE Feedback (
    id INT AUTO_INCREMENT PRIMARY KEY,
    itemId INT NOT NULL,
    userId INT NOT NULL,
    rating INT NOT NULL,
    comment TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (itemId) REFERENCES Items(id),
    FOREIGN KEY (userId) REFERENCES Users(id)
);
