server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/master
  application:
    name: "XianweiECommerce"
  cloud:
    inetutils:
      ignored-interfaces: ".*"
      default-hostname: localhost
      default-ip-address: 127.0.0.1


  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: wxwwxw123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

keycloak:
  realm: master
  resource: xianwei-ecommerce-monolith
  auth-server-url: http://localhost:7080
  ssl-required: external
  credentials:
    secret: xaKni1LX1YOhB7WtuhEcpI6nf9akqD66
  use-resource-role-mappings: true
  principal-attribute: xianwei

