server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/master
  application:
    name: "XianweiECommerce"

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: wxwwxw123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
