apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: gatewayserver
  name: gatewayserver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: gatewayserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /prometheus/metrics
        prometheus.io/port: "9400"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        k8s-app: gatewayserver
      name: gatewayserver
    spec:
      containers:
      -   name: gatewayserver
          image: xianwew/ecommerce:gatewayserver
          imagePullPolicy: IfNotPresent
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
