global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8080' ]

  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'user:8070' ]

  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order:8050' ]

  - job_name: 'item'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'item:8040' ]

  - job_name: 'payment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'payment:8060' ]

  - job_name: 'eurekaserver1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver1:8761' ]

  - job_name: 'eurekaserver2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver2:8762' ]

  - job_name: 'eurekaserver3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver3:8763' ]

  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8090' ]

  
