server:
  port: 8040

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true

spring:
  application:
    name: "Item"
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8090/"
  cache:
    type: redis
  data:
    redis:
      sentinel:
        master: redis-master
        nodes: "redis-sentinel1:26379,redis-sentinel2:26380,redis-sentinel3:26381"
      password: wxwwxw123
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          test-on-borrow: true

search:
  items:
    cache:
      refresh:
        rate: 15000
      initial:
        delay: 10000

cloudinary:
  cloud-name: dl7atizzb
  api-key: 145491984531442
  api-secret: 1iZYfLLIkyl9QGDTreYx3r-5Mcc
  avatar-upload-folder: XianweiECommerce/UserAvatar
  category-upload-folder: XianweiECommerce/Category
  item-upload-folder: XianweiECommerce/Item

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}