version: '3.8'

services:
  userservice:
    image: mysql:latest
    container_name: userservice
    environment:
      MYSQL_ROOT_PASSWORD: wxwwxw123
      MYSQL_DATABASE: userservice
    ports:
      - "3306:3306"
    volumes:
      - userservice_data:/var/lib/mysql
    command: >
      sh -c "echo 'CREATE DATABASE IF NOT EXISTS userservice;' > /docker-entrypoint-initdb.d/init.sql && docker-entrypoint.sh mysqld"

  orderservice:
    image: mysql:latest
    container_name: orderservice
    environment:
      MYSQL_ROOT_PASSWORD: wxwwxw123
      MYSQL_DATABASE: orderservice
    ports:
      - "3307:3306"
    volumes:
      - orderservice_data:/var/lib/mysql
    command: >
      sh -c "echo 'CREATE DATABASE IF NOT EXISTS orderservice;' > /docker-entrypoint-initdb.d/init.sql && docker-entrypoint.sh mysqld"

  itemservice:
    image: mysql:latest
    container_name: itemservice
    environment:
      MYSQL_ROOT_PASSWORD: wxwwxw123
      MYSQL_DATABASE: itemservice
    ports:
      - "3308:3306"
    volumes:
      - itemservice_data:/var/lib/mysql
    command: >
      sh -c "echo 'CREATE DATABASE IF NOT EXISTS itemservice;' > /docker-entrypoint-initdb.d/init.sql && docker-entrypoint.sh mysqld"

volumes:
  userservice_data:
  orderservice_data:
  itemservice_data:
